### PR TITLE
regenerate sdk

### PR DESCRIPTION
**Pull request by SwampDragons**
### :hammer_and_wrench: Description

Regenerated the cloud-packer-service client. 

The main purpose was to add the SourceImageID field to the CreateBuild and UpdateBuild endpoints. 

But it is bigger than that because in the intervening time, we switched to prefixing the proto files which changed the names of all the pieces in the SDK. 

We changed the prefixing because it made life easier for the folks generating the Packer service api docs. 

### :ship: Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/hcp-sdk-go/blob/main/CHANGELOG.md):

```release-note
Updated SDK to add SourceImageID field to the UpdateBuild and CreateBuild endpoints. 
```

### :+1: Definition of Done

- [ ] <service> SDK added
- [x] <service> SDK updated
- [ ] Tests added?
- [ ] Docs updated?

### CODE REVIEW

**Review by sylviamoss — APPROVED** [review]

**Review by roaks3 — APPROVED** [review]
LGTM!

I did want to call out since it isn't in the changelog section of the PR, but I believe the rename for certain objects (eg. `CreateBucketParams` -> `PackerServiceCreateBucketParams`) will result in a breaking change for the sdk release.

**Comment by SwampDragons** [comment]
Yes, I realized that. I think it's ok since the SDK is only used internally; I can go in and fix the terraform provider today.

**Comment by roaks3** [comment]
Oh gotcha! My note was mainly intended to surface that change if another developer ended up cutting the release, but if you're following the change through then you can ignore me 😄 . No concerns from my end!

**Comment by SwampDragons** [comment]
Sounds good. :D

**Pull request merged**
