### PR TITLE
Updated consul service with instructions

### PR DESCRIPTION
**Pull request by i0rek**
### :hammer_and_wrench: Description

Updated Consul Service to add new field `primary` and new tier `plus`. Followed https://hashicorp.atlassian.net/wiki/spaces/CLOUD/pages/1523744830/Go+SDK. Needs https://github.com/hashicorp/cloud-api/pull/45.

This is what I did:

1. `git clone git@github.com:hashicorp/cloud-api.git`
1. `git clone git@github.com:hashicorp/hcp-sdk-go.git`
1. `cd cloud-api`
1. `cp ../cloud-consul-service/proto-public/20210204/swagger/hcp.swagger.json specs/cloud-consul-service/preview/2021-02-04/consul.swagger.json`
1. `GO111MODULE=off go get ./...`
1. `GO111MODULE=off make`

Somehow this resulted in a LOT of changes.

### :ship: Release Note
Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-hcp/blob/main/CHANGELOG.md):

```release-note
...
```

### :+1: Definition of Done

- [ ] <service> SDK added
- [ ] <service> SDK updated
- [ ] Tests added?
- [ ] Docs updated?

### CODE REVIEW

**Comment by i0rek** [comment]
🤔 Not sure why this test is failing...

**Comment by bcmdarroch** [comment]
Hm that is an odd failure, I'll investigate.

**Comment by i0rek** [comment]
Thanks @bcmdarroch!
Providing some context as to why I think this error is strange: it errors for an older API version that I didn't touch and complains about a field that should be `readonly`. Even more strange is that this field is marked as `readonly` in the corresponding swagger file.

I just copied over the most recent swagger file from `consul-service` for the old API version and ran `make` in `cloud-api`. But that didn't change anything in `hcp-sdk-go`.

**Review by bcmdarroch — APPROVED** [review]
Fixed this up by regenerating on v0.25.0 of go-swagger, so now this only touches the relevant Consul files. To keep these changes separate and distinct, I'll follow up with a regen of the whole SDK using the latest v0.27.0.

For folks watching at home, the original CI error was due to the go-openapi/validate package being out of date, so there's some bonus dependency bumps in this PR.

**Pull request merged**
